### ISSUE TITLE
Failing tests with ember 3.11 beta

### ISSUE THREAD

**Issue by GavinJoyce** [adopted-ember-addons/ember-cp-validations#642]
The `beta` and `canary` scenarios are failing in https://github.com/offirgolan/ember-cp-validations/pull/641 with the following errors:

```
not ok 46 Chrome 74.0 - [38 ms] - Integration | Validations | Factory - General: call super in validations class with no super property
    ---
        actual: >
            null
        stack: >
            Error: Assertion Failed: An EmberObject based class, (unknown), was not instantiated correctly. You may have either used `new` instead of `.create()`, or not passed arguments to your call to super in the constructor: `super(...arguments)`. If you are trying to use `new`, consider using native classes without extending from EmberObject.
                at assert (http://localhost:7357/assets/vendor.js:43163:17)
                at Class.CoreObject (http://localhost:7357/assets/vendor.js:36333:32)
                at Class.EmberObject (http://localhost:7357/assets/vendor.js:37242:26)
                at Class.DebugFrameworkObject (http://localhost:7357/assets/vendor.js:37334:32)
                at Class (http://localhost:7357/assets/vendor.js:36699:24)
                at new Class (http://localhost:7357/assets/vendor.js:36699:24)
                at Function.create (http://localhost:7357/assets/vendor.js:36766:20)
                at _default (http://localhost:7357/assets/tests.js:242:16)
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:1504:49)
                at runTest (http://localhost:7357/assets/test-support.js:4400:30)
```

**Comment by fsmanuel** [comment]
@GavinJoyce Is this still a problem with the latest beta release?
